spring:
  datasource:
    #    url: "jdbc:postgresql://localhost:5432/quotes"
    url: ${DB_URL}
    #    username: postgres
    username: ${DB_USERNAME}
    #    password: postgres
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:dbchangelog/changelog-master.yaml

quotes:
  cron: ${QUOTES_CRON}