spring:
  datasource:
    #    url: "jdbc:postgresql://postgres:5432/quotes"
    url: ${DB_URL}
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:dbchangelog/changelog-master.yaml

quotes:
  cron: ${QUOTES_CRON}